name: tsf
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - ca-certificates=2024.7.2=h06a4308_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuv=1.48.0=h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.4=h6a678d5_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy-base=1.24.3=py38h31eccc5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=24.0=py38h06a4308_0
  - python=3.8.0=h0371630_2
  - readline=7.0=h7b6447c_5
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.0.1
      - ace-tools==0.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - axial-positional-embedding==0.2.1
      - backcall==0.2.0
      - blosc2==2.0.0
      - cachetools==5.4.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.12
      - datasets==3.1.0
      - decorator==5.2.1
      - deprecated==1.2.14
      - dill==0.3.8
      - docopt==0.6.2
      - einops==0.5.0
      - executing==2.1.0
      - filelock==3.16.1
      - fonttools==4.53.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - google-auth==2.32.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.65.1
      - huggingface-hub==0.29.3
      - idna==3.7
      - importlib-metadata==8.0.0
      - importlib-resources==6.4.0
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.1
      - joblib==1.4.2
      - kagglehub==0.2.9
      - kiwisolver==1.4.5
      - llvmlite==0.41.1
      - local-attention==1.4.4
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.0
      - matplotlib-inline==0.1.7
      - mkl-service==2.4.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - numba==0.58.1
      - numexpr==2.8.6
      - numpy==1.23.5
      - oauthlib==3.2.2
      - packaging==24.1
      - pandas==1.5.3
      - parso==0.8.4
      - patool==1.12
      - patsy==1.0.1
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pipreqs==0.4.13
      - prettytable==3.10.2
      - product-key-memory==0.1.10
      - prompt-toolkit==3.0.47
      - propcache==0.2.0
      - protobuf==5.27.2
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.19.1
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.2
      - reformer-pytorch==1.4.4
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - safetensors==0.5.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sktime==0.16.1
      - stack-data==0.6.3
      - statsmodels==0.14.1
      - sympy==1.11.1
      - tables==3.8.0
      - tcmlib==1.2.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tomli==2.2.1
      - torch==1.11.0+cu113
      - torchinfo==1.8.0
      - torchvision==0.12.0+cu113
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.11.0
      - urllib3==2.2.2
      - wcwidth==0.2.13
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarg==0.1.10
      - yarl==1.15.2
      - zipp==3.19.2